[build]
  builder = "NIXPACKS"
  buildCommand = "npm run build"

[deploy]
  startCommand = "npm start"
  healthcheckPath = "/"
  restartPolicyType = "ON_FAILURE"
  numReplicas = 1

[variables]
  NEXT_PUBLIC_API_URL = "https://file-compressor-production-ef6a.up.railway.app" 